/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package imageprocessing;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author B.K.D.Vibodha
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    ImageHandler imageHandler = ImageHandler.getInstance();
    int currentImage = -1;
    int briVal = 0;
    
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_open = new javax.swing.JButton();
        btn_undo = new javax.swing.JButton();
        btn_redo = new javax.swing.JButton();
        txt_fileLocation = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbl_image = new javax.swing.JLabel();
        btn_dither = new javax.swing.JButton();
        btn_nearest = new javax.swing.JButton();
        combo_scale_ne = new javax.swing.JComboBox();
        combo_state_ne = new javax.swing.JComboBox();
        btn_linear = new javax.swing.JButton();
        combo_state_li = new javax.swing.JComboBox();
        txt_scale = new javax.swing.JTextField();
        btn_ro_anti = new javax.swing.JButton();
        btn_ro_clock = new javax.swing.JButton();
        btn_flip = new javax.swing.JButton();
        btn_negative = new javax.swing.JButton();
        btn_redu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_mean = new javax.swing.JButton();
        btn_mid = new javax.swing.JButton();
        btn_prew = new javax.swing.JButton();
        combo_prew = new javax.swing.JComboBox();
        txt_tr = new javax.swing.JTextField();
        btn_sobel = new javax.swing.JButton();
        btn_lap = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_open.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_open.setText("Open");
        btn_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openActionPerformed(evt);
            }
        });

        btn_undo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_undo.setText("Undo");
        btn_undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_undoActionPerformed(evt);
            }
        });

        btn_redo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_redo.setText("Redo");
        btn_redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redoActionPerformed(evt);
            }
        });

        txt_fileLocation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jScrollPane2.setViewportView(lbl_image);

        btn_dither.setText("Dither");
        btn_dither.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ditherActionPerformed(evt);
            }
        });

        btn_nearest.setText("Nearest Neibour");
        btn_nearest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nearestActionPerformed(evt);
            }
        });

        combo_scale_ne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "4", "8", "16" }));

        combo_state_ne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Up", "Down" }));

        btn_linear.setText("Linear");
        btn_linear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_linearActionPerformed(evt);
            }
        });

        combo_state_li.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Up", "Down" }));

        txt_scale.setMaximumSize(new java.awt.Dimension(69, 22));
        txt_scale.setMinimumSize(new java.awt.Dimension(69, 22));

        btn_ro_anti.setText("Rotate Anti Clock");
        btn_ro_anti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ro_antiActionPerformed(evt);
            }
        });

        btn_ro_clock.setText("Rotate Clock");
        btn_ro_clock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ro_clockActionPerformed(evt);
            }
        });

        btn_flip.setText("Flip");
        btn_flip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flipActionPerformed(evt);
            }
        });

        btn_negative.setText("Digital Negative");
        btn_negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_negativeActionPerformed(evt);
            }
        });

        btn_redu.setText("-");
        btn_redu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reduActionPerformed(evt);
            }
        });

        jLabel1.setText("Brightness");

        btn_add.setText("+");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_mean.setText("Mean Filter");
        btn_mean.setToolTipText("");
        btn_mean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_meanActionPerformed(evt);
            }
        });

        btn_mid.setText("Medium Filter");
        btn_mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_midActionPerformed(evt);
            }
        });

        btn_prew.setText("Prewwitt");
        btn_prew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prewActionPerformed(evt);
            }
        });

        combo_prew.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Horizontal", "Verticle" }));

        txt_tr.setMaximumSize(new java.awt.Dimension(69, 22));
        txt_tr.setMinimumSize(new java.awt.Dimension(69, 22));

        btn_sobel.setText("Sobel");
        btn_sobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sobelActionPerformed(evt);
            }
        });

        btn_lap.setText("Laplasian");
        btn_lap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_dither)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_linear)
                                        .addGap(37, 37, 37)
                                        .addComponent(txt_scale, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_nearest)
                                        .addGap(18, 18, 18)
                                        .addComponent(combo_scale_ne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(combo_state_ne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_state_li, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_ro_anti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ro_clock))
                            .addComponent(btn_flip)
                            .addComponent(btn_negative)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_redu)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_add))
                            .addComponent(btn_mean)
                            .addComponent(btn_mid)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_sobel)
                                    .addComponent(btn_prew)
                                    .addComponent(btn_lap))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(combo_prew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_tr, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_open)
                        .addGap(27, 27, 27)
                        .addComponent(txt_fileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_undo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_redo)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_open)
                    .addComponent(txt_fileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_undo)
                    .addComponent(btn_redo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_dither)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_nearest)
                            .addComponent(combo_scale_ne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_state_ne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_linear)
                            .addComponent(txt_scale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_state_li, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ro_anti)
                            .addComponent(btn_ro_clock))
                        .addGap(39, 39, 39)
                        .addComponent(btn_flip)
                        .addGap(34, 34, 34)
                        .addComponent(btn_negative)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_redu)
                            .addComponent(jLabel1)
                            .addComponent(btn_add))
                        .addGap(39, 39, 39)
                        .addComponent(btn_mean)
                        .addGap(18, 18, 18)
                        .addComponent(btn_mid)
                        .addGap(18, 18, 18)
                        .addComponent(btn_prew)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btn_sobel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo_prew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_lap)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChoser = new JFileChooser("C:\\Windows\\Web\\Screen");
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".png","jpeg","jpg");
        fileChoser.setFileFilter(filter);
        if(fileChoser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file = fileChoser.getSelectedFile();
            String fileName = file.getPath();
            txt_fileLocation.setText(fileName);
            
            try {
                imageHandler.setImage(file);
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            setImage(imageHandler.getImage());
            currentImage = 0;
        }             
        
    }//GEN-LAST:event_btn_openActionPerformed

    private void btn_ditherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ditherActionPerformed
        // TODO add your handling code here:
        Sampling sampling = new Sampling();
        Image newImage = sampling.dither(imageHandler.getImage());
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_ditherActionPerformed

    private void btn_undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_undoActionPerformed
        // TODO add your handling code here:
       
        if(currentImage>-1){
           // System.out.println("undo");
         Image newImage = imageHandler.undo(currentImage);
        if(newImage!=null){
            System.out.println("undo");
            setImage(newImage);
        }   
        }
        
    }//GEN-LAST:event_btn_undoActionPerformed

    private void btn_redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redoActionPerformed
        // TODO add your handling code here:
        if(currentImage>-1){
            Image newImage = imageHandler.redo(currentImage);
            if(newImage!=null){
                setImage(newImage);
            }
        }
    }//GEN-LAST:event_btn_redoActionPerformed

    private void btn_nearestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nearestActionPerformed
        // TODO add your handling code here:
        Sampling sampling = new Sampling();
        int scale = (int) Math.pow(2,combo_scale_ne.getSelectedIndex()+1);
        String state = "down";
        if(combo_state_ne.getSelectedIndex()==0){
            state = "up";
        }
        Image newImage = sampling.nearestNeibour(imageHandler.getImage(),scale,state);
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_nearestActionPerformed

    private void btn_linearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_linearActionPerformed
        // TODO add your handling code here:
        Sampling sampling = new Sampling();
        double scale = Double.parseDouble(txt_scale.getText());
        String state = "down";
        if(combo_state_li.getSelectedIndex()==0){
            state = "up";
        }
        Image newImage = sampling.linearIn(imageHandler.getImage(),scale,state);
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_linearActionPerformed

    private void btn_ro_antiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ro_antiActionPerformed
        // TODO add your handling code here:
        PointOp pointOp = new PointOp();
        Image newImage = pointOp.rotateAnti(imageHandler.getImage());
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_ro_antiActionPerformed

    private void btn_ro_clockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ro_clockActionPerformed
        // TODO add your handling code here:
        PointOp pointOp = new PointOp();
        Image newImage = pointOp.rotateClock(imageHandler.getImage());
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_ro_clockActionPerformed

    private void btn_flipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flipActionPerformed
        // TODO add your handling code here:
        PointOp pointOp = new PointOp();
        Image newImage = pointOp.flip(imageHandler.getImage());
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_flipActionPerformed

    private void btn_negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_negativeActionPerformed
        // TODO add your handling code here:
        PointOp pointOp = new PointOp();
        Image newImage = pointOp.negative(imageHandler.getImage());
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_negativeActionPerformed

    private void btn_reduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reduActionPerformed
        // TODO add your handling code here:
       
        //System.out.println(briVal);
        PointOp pointOp = new PointOp();
        Image newImage = pointOp.bright(imageHandler.getImage(),-2);
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_reduActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
       
        //System.out.println(briVal);
        PointOp pointOp = new PointOp();
        Image newImage = pointOp.bright(imageHandler.getImage(),2);
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_meanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_meanActionPerformed
        // TODO add your handling code here:
        Filter filter = new Filter();
        Image newImage = filter.meanFilter(imageHandler.getImage());
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_meanActionPerformed

    private void btn_midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_midActionPerformed
        // TODO add your handling code here:
        Filter filter = new Filter();
        Image newImage = filter.midFilter(imageHandler.getImage());
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_midActionPerformed

    private void btn_prewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prewActionPerformed
        // TODO add your handling code here:
        EdgeDetection edgeDetection = new EdgeDetection();
        String state = "h";
        if(combo_prew.getSelectedIndex()==1){
            state="v";
        }
        int tr = Integer.valueOf(txt_tr.getText());
        Image newImage = edgeDetection.prewwitt(imageHandler.getImage(), state,tr);
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_prewActionPerformed

    private void btn_sobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sobelActionPerformed
        // TODO add your handling code here:
        EdgeDetection edgeDetection = new EdgeDetection();
        String state = "h";
        if(combo_prew.getSelectedIndex()==1){
            state="v";
        }
        int tr = Integer.valueOf(txt_tr.getText());
        Image newImage = edgeDetection.sobel(imageHandler.getImage(), state,tr);
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_sobelActionPerformed

    private void btn_lapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapActionPerformed
        // TODO add your handling code here:
        EdgeDetection edgeDetection = new EdgeDetection();
        String state = "+";
        if(combo_prew.getSelectedIndex()==1){
            state="-";
        }
        int tr = Integer.valueOf(txt_tr.getText());
        Image newImage = edgeDetection.laplasian(imageHandler.getImage(), state,tr);
        imageHandler.evolveImage(newImage);
        setImage(imageHandler.getImage());
    }//GEN-LAST:event_btn_lapActionPerformed
    

    private void setImage(Image image){
        currentImage = image.getId();
        //System.out.println(currentImage);
        lbl_image.setSize(image.getBufferedImage().getWidth(), image.getBufferedImage().getHeight());
        
        lbl_image.setIcon(new ImageIcon(image.getBufferedImage()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_dither;
    private javax.swing.JButton btn_flip;
    private javax.swing.JButton btn_lap;
    private javax.swing.JButton btn_linear;
    private javax.swing.JButton btn_mean;
    private javax.swing.JButton btn_mid;
    private javax.swing.JButton btn_nearest;
    private javax.swing.JButton btn_negative;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton btn_prew;
    private javax.swing.JButton btn_redo;
    private javax.swing.JButton btn_redu;
    private javax.swing.JButton btn_ro_anti;
    private javax.swing.JButton btn_ro_clock;
    private javax.swing.JButton btn_sobel;
    private javax.swing.JButton btn_undo;
    private javax.swing.JComboBox combo_prew;
    private javax.swing.JComboBox combo_scale_ne;
    private javax.swing.JComboBox combo_state_li;
    private javax.swing.JComboBox combo_state_ne;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTextField txt_fileLocation;
    private javax.swing.JTextField txt_scale;
    private javax.swing.JTextField txt_tr;
    // End of variables declaration//GEN-END:variables
}
